# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=512, unique=True)),
                ("from_address", models.CharField(max_length=512)),
                ("subject", models.CharField(blank=True, max_length=512)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("event_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
